### ISSUE TITLE
Am I missing something? $el still exists.

### ISSUE THREAD

**Issue by SomethingSexy** [akre54/Backbone.NativeView#12]
Since Backbone.NativeView is not overriding _ensureElement, if I am using Backbone.NativeView directly, $el still exists.  Which isn't a problem per say, but your documentation says otherwise.

**Comment by akre54** [comment]
Are you using the master branch of Backbone? There hasn't yet been a tagged release of Backbone with the necessary changes (jashkenas/backbone#3003) so in the interim you should point your package manager to the current git hash.

> Since Backbone.NativeView is not overriding _ensureElement

We override `_setElement` (a new method from pull 3003) which gets called from `setElement` (and `_ensureElement` in turn). No $el property is created.

**Comment by SomethingSexy** [comment]
Ah that makes sense, I didn't see that being mentioned.  I am running off 1.1.2.

**Comment by ropbla9** [comment]
Tyle, make native version of Can JS or Sammy.js. I hate jQuery and my
favorite frameworks run on top of it, haha.

2015-02-13 23:39 GMT-03:00 Tyler Cvetan <notifications@github.com>:

**Comment by SomethingSexy** [comment]
@akre54 have they given you any idea of when 1.2.0 is coming out?

**Comment by akre54** [comment]
Hopefully soon. There's a thread in the backbone issues that you promoted
me to restart that you can check out and chime in on if you like. We just
need to document all the changes and figure out what else will make it in
for 1.2.0

**Comment by akre54** [comment]
Backbone 1.2.0 is out! Test away!

**Comment by SomethingSexy** [comment]
Boom! Thanks.  I will pick this back up.
