### ISSUE TITLE
Exoskeleton + Browserify

### ISSUE THREAD

**Issue by antwan1986** [akre54/Backbone.NativeView#13]
I see this issue has come up a few times and in the tickets logged there's never really been a resolution. I've followed the instructions here (https://github.com/paulmillr/exoskeleton/wiki/Exoskeleton-without-jQuery) regarding how it should be handled from a Browserify / CommonJS perspective but I constantly get errors even when using aliasify.

The problem seems to be that Aliasify is not transforming anything in `node_modules` that we call as dependencies, so the reference to `backbone` inside your library never seems to get rewritten. The "recipe" in the link posted above, have you verified that it works and have a code example that I could pull?

I've logged a ticket with Aliasify:
https://github.com/benbria/aliasify/issues/25

**Comment by akre54** [comment]
Looks like the global option solves this issue, right?

**Comment by antwan1986** [comment]
Seems to yes, perhaps your code snippet in the link of my original post could be updated. Also:
```
Backbone.View = require('backbone.nativeview');
```

Doesn't seem to work because it returns a blank object. The solution that worked for me was:
```
require('backbone.nativeview');
Backbone.View = Backbone.NativeView;
```

**Comment by akre54** [comment]
Link me? Or feel free to open a pull / update the wiki

**Comment by antwan1986** [comment]
Unsure how I had access to the Exoskeleton wiki, but changes can be seen here:
https://github.com/paulmillr/exoskeleton/wiki/Exoskeleton-without-jQuery/_compare/3f3a04b492d710b7d1178d49a05c64ed17ecdc67%5E...3f3a04b492d710b7d1178d49a05c64ed17ecdc67

**Comment by akre54** [comment]
I don't know about the "problematic" wording but otherwise thanks. Next
step is to add webpack instructions.
