### ISSUE TITLE
Integrating into core backbonejs

### ISSUE THREAD

**Issue by SylvainCorlay** [akre54/Backbone.NativeView#21]
Is there any plan to make NativeView part of backbonejs, as a sort of base view.

Would it make sense in the same occasion to deprecate the original `Backbone.View`, and point developers to some `Backbone.$View` instead in the case of jQuery?

**Comment by akre54** [comment]
Not for a while. The jQuery version is simply good enough and easier to use for most people. If people start abandoning jQuery en masse then perhaps.
