### ISSUE TITLE
Working with require()'s

### ISSUE THREAD

**Issue by mbrevda** [akre54/Backbone.NativeView#22]
Im trying to load NativeView with require() but didnt see a guide on that. Being that everything I tried failed, can you please show how to do that?

I tried:
```js
var Backbone = require('backbone'),
    _ = require('underscore'),
    NativeView = require('backbone.nativeview')

module.exports = Backbone.View.extend(Backbone.NativeViewMixin, {
```
```js
var Backbone = require('backbone'),
    _ = require('underscore'),
    NativeView = require('backbone.nativeview')

module.exports = NativeView.extend({
```
```js
var Backbone = require('backbone'),
    _ = require('underscore'),
    NativeView = require('backbone.nativeview')

module.exports = Backbone.NativeView.extend({
```
amongst other. While `Backbone.View = NativeView` works, this is for a library and I dont want to force NativeView to be global. When running [tests](https://github.com/mbrevda/backbone-kinview/blob/master/tests/viewsTest.js), I'm getting:

```
 9) View Attach to:
     TypeError: Expecting a function in instanceof check, but got undefined
      at _.extend._setElement (node_modules/backbone/backbone.js:1253:40)
      at _.extend.setElement (node_modules/backbone/backbone.js:1242:12)
      at _.extend._ensureElement (node_modules/backbone/backbone.js:1322:14)
      at new Backbone.View (node_modules/backbone/backbone.js:1190:10)
      at Context.<anonymous> (tests/viewsTest.js:110:20)
```

**Comment by akre54** [comment]
I'm not sure what you're trying to do? Your first example is unnecessary. [The NativeView `exports` object is simply `Backbone.NativeView`](https://github.com/akre54/Backbone.NativeView/blob/0.3.3/backbone.nativeview.js#L168) (equivalent to `var MyView = Backbone.View.extend(Backbone.NativeViewMixin)`). 

Obviously if you override Backbone.View it will break for other libraries. Your [KinView class](https://github.com/mbrevda/backbone-kinview/blob/df3ecd509ffa31431563828a8e4a3f07ac617ea4/src/views/kin.js) looks like it's using both NativeView and Backbone.View. I'd say pick one or the other.

If your library relies on NativeView, simply replace the `Backbone.View` lines with `NativeView`. But from a quick glance it doesn't look look like it's using any NativeView-specific features. If I were you I would either export your code as a mixin (like NativeView does), or extend from Backbone.View and have consumers of your library extend their views with NativeViewMixin.

This is a limitation of single-inheritance object oriented design to be sure, but there are solutions. They can definitely coexist in the same project.

**Comment by mbrevda** [comment]
KinView *is* the library. I'm trying to have it work without requiring jquery, while still being compatible (i.e. useable) by other projects that **will** want Backbone + jQuery. Is that possible or did I misunderstand?

**Comment by akre54** [comment]
Yeah nothing in there looks specific to NativeView *or* jQuery. And the goal of pulling out jQuery from Backbone is that projects like this should be agnostic about what DOM manipulation lib they're using under the hood. 

I wouldn't recommend relying on NativeView in your project, it's not really meant to be *extended* by libraries. The view is meant to be *called* by libraries (hence the common interface with Backbone), but that's up to your library's consumer to decide.

A couple notes: instead of `this.el.querySelector(opts.to)`, use `this.$(opts.to)[0]`. Instead of `model.get('view').el.addEventListener(...)` use `model.get('view').delegate(...)`. Your code will work fine with or without jQuery (on a relatively modern browser with el.querySelector and addEventListener), but using the standard interface helps keep things clean somewhat.

**Comment by mbrevda** [comment]
I'm not sure I follow the general idea. Are you saying that libs (like KinView) should extend Backbone.View, but as long as they don't use jquery specific code, the consumers can later use NativeView without needing jquery?

**Comment by mbrevda** [comment]
I've [updated KinView](https://github.com/mbrevda/backbone-kinview/commit/78453b3e8cee39e62b285db855650d67a373a8e1) with your suggestions

**Comment by akre54** [comment]
> Are you saying that libs (like KinView) should extend Backbone.View, but as long as they don't use jquery specific code, the consumers can later use NativeView without needing jquery?

Yup, exactly. In fact, you probably shouldn't have KinView depend on jQuery directly in the `dependencies` field in KinView's package.json.

A consumer of your library might want to load jQuery or NativeView, but your library doesn't use either directly: the underlying DOM manipulation implementation shouldn't matter to KinView.

To test your library, just add jQuery or NativeView in `devDependencies`. It will be available while you develop and test but you won't force an extra dependency on apps that use your library.

**Comment by mbrevda** [comment]
Thanks a ton!
