### ISSUE TITLE
Blur/Focus do not bubble up and therefore not accessible via this.delegate

### ISSUE THREAD

**Issue by dsheiko** [akre54/Backbone.NativeView#27]
Blur/Focus  are special events (http://www.quirksmode.org/blog/archives/2008/04/delegating_the.html)
As they do not bubble up one can not subscribe to them by using `this.delegate` or `this.events`
I assume here required a trick to emulate the delegation

**Comment by akre54** [comment]
Dupe of #26. Let's discuss fixes there.
